# Generated by Django 2.2.1 on 2020-03-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('male', 'male'), ('female', 'female')], default='SELECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('male', 'male'), ('female', 'female')], default='SELECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='phamarcist',
            name='gender',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('male', 'male'), ('female', 'female')], default='SELECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='gender',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('male', 'male'), ('female', 'female')], default='SELECT', max_length=100),
        ),
    ]
