# Generated by Django 2.2.1 on 2020-03-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200321_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bio',
        ),
        migrations.AddField(
            model_name='appointment',
            name='receptionist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.Receptionist'),
        ),
    ]
